### ISSUE TITLE
Can't start up the example app

### ISSUE THREAD

**Issue by FromStoneage** [elasticrash/Angular.io.MapViewer#26]
Great work on the angular2 Leaflet component, want to try it out and wasn't able to add a component to my angular2 app following the basic documentation.

I want to see how this example app works and unfortunately not able to start up. Any help is appreciated!

I'm running the example app off `angular-cli-example` branch

`npm start` gives the following error.

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: b1a33d3995448eee78c8                                                               
Time: 36141ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 72.9 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 57.7 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.24 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /home/jonathan/Documents/Github/Angular.io.MapViewer/node_modules/ngx.leaflet.components/node_modules/@angular/core/core.d.ts, resolving symbol ngxLeafletModule in /home/jonathan/Documents/Github/Angular.io.MapViewer/node_modules/ngx.leaflet.components/ngx.leaflet.module.ts, resolving symbol ngxLeafletModule in /home/jonathan/Documents/Github/Angular.io.MapViewer/node_modules/ngx.leaflet.components/ngx.leaflet.module.ts
webpack: Failed to compile.
```
any ideas?

Thanks!

**Comment by FromStoneage** [comment]
ok, that appears to be an angular CLI bug if you save any file once more and retrigger the build-chain it would work again.

**Comment by elasticrash** [comment]
The problem is that CLI (webpack) doesn't fully support certain syntaxes. So the app cannot be statically analyzed before aot build. Recompile does not statically reanalyses the app, so thats why it works afterwards.

I am familiar with the error. I had it on other apps as well, and I know my way around it. It's annoying how so many things are not fully compatible with cli/webpack.


There is this handy list (which isn't exactly up to date) but you should get the idea, if you are interested.

https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts
